security:
  jwt:
    secret-key: ENC(LBWMFF6yyJly33LZxXu0qNokIu5g+JPWa9RBQW6dIDvT2+aWmijshKbnBG6gD6EFn9Fyq+3cugQnMXk6TD1s7zpK7OpU7PX1N8A8orfAGXsOiOCpOaMuh2sI2WeMk6RzGMVbapmpYyER1cKNzEE0ppMCXTzxzPXQsRiBhiHf4n17rcsFxBWPWhC2UDYb2sUI)
