security:
  jwt:
    secret-key: ENC(KWjnpWV25BiKGBfMDSYDiFT7aMHiGbzj3a/kRsyRpTJdkR+JrM6RnVJZWcfUaFusgVdkXB0ZTxGsGLOKsdTC0LpTRaJeZEMTz6ySEM3iOtsxiUpTYnyvA9V8jQDTdQoduSj53w1F5rRMMSksS08hFmOi+atwIDzLbF046YSzybzUIZ21beOrlPfDj5ENf7Sl)
