spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: ENC(1yDzJNmIjjxr2natwJ+2hI/z+w5tlzkLuTzpmctyqcKuAFSowZrr5cki3VSYWob/ygbD7ksCTLib70Aqx9MxDg==)
          kakao:
            redirect-uri: ENC(OKB1DkhKLto1VF8SkBdbump/YLgAukeowH3CS5z6lHPt3shQnvRfxedR88jTeTaHHtRhetIvrPxP1CGOKBIR2A==)

oauth2:
  success:
    redirect_uri: 'http://localhost:3000'
