spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: ENC(2yqMAMisnVRmZDR0W0nrFXFHASyJ3CWqth2S+LWBHSiJ1swupyBPgUbHGPzzQRnk4RqsnddbQZ7sEGtfx2t/Iw==)
          kakao:
            redirect-uri: ENC(0tnMuUU2iNEQaBWqqrKW9EflgTCVJdimdvLvK0jpb73grlg11/5Xlz1dUGNIXdd28BgBauNfqqD6EqFgoZVSAg==)

oauth2:
  success:
    redirect_uri: 'https://dev.gohigher.site'
