spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: http://api.dev.gohigher.site:8080/oauth2/callback/google
          kakao:
            redirect-uri: http://api.dev.gohigher.site:8080/oauth2/callback/kakao

oauth2:
  success:
    redirect_uri: 'http://api.dev.gohigher.site:8080'
