spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: ENC(oh0IKLmsy0Ad4VH1jvY7MkT3OBBpFIRIvilYoSm/C3MNjXU5OoV4CD8XfIoJFoi+ZkXF7arJ1dAYbSjNvn1WcA==)
          kakao:
            redirect-uri: ENC(ZTAVPYVX4DAazNUebfu+QQ4eN/h7vLPIZWcemKZk9ODyPT44JGJgTHTB5T55jS6iS/JQHh5UI0FzAFVkXTv+KQ==)

oauth2:
  success:
    redirect_uri: 'http://localhost:3000'
