spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(cx7OYawVMleYVKerl15i5/vGXJ8lup66eycRn5yBRCA1H5GhPiFelR1OptANOsUdj4W/mrIVCqD6ESXz5CawGZ5u8lrBPmYcmkLCuTRGdlEgKopZhZjwtQ==)
            client-secret: ENC(FbW+6olqQLswd0X/Y6Xhd0PJ38dGfcblCoodHdEhZJXFfCxlbp90saJFaWMLIPAf)
            scope: email
          kakao:
            client-id: ENC(qDNL3VhDV23d0b86RkR6oYX+58QsCGd+XD3S8PvER4ZCWwAzen40h4iVfC7HVqRy)
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

token:
  request:
    uri: '/token'
