spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: ENC(PayLYuevrcKy94mwzodmmm3Vt1d0A3HBNNq1HOqE8hwq+YvhHzb/G2Oxr3dheZh2bQz8RBSsRLoHqa36Y1B5pQ==)
          kakao:
            redirect-uri: ENC(dOnbIdYKlab2kfhVdYxj7GzSXff686uJM1WEXDVMFh8CeNm4JL3GoTX+EXg3tPbKYA7XF92JnPkoTwV0SpY+Uw==)

oauth2:
  success:
    redirect_uri: 'http://localhost:3000'
