spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: ENC(zNDyE6OcetPJhZIozxa/fFoCWeoscY+/IZcywLvXIMz+usBUh4B39RJmMDq/IN02BJC7+/jkpC5p1G1FSoF3SA==)
          kakao:
            redirect-uri: ENC(MJwB7oqUdfLKNn7738anGKVJ860QQlP/H8tWOpIl9QjKuubPy7iV3ZfFZfjgcJkjrHs0jCIKnJEJLkkIq4QH0w==)

oauth2:
  success:
    redirect_uri: 'https://dev.gohigher.run'
