spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(h47JjPyAlcc6k1vudWNektC6cc6kjKOOZ7V+U0jKhS747qx++/EriOgP3ND49HA8F6CCzfxA4l0ftb60cKBodqBwB+5binG+SxhV4+0xaN5aGmHHOMf6tA==)
            client-secret: ENC(tKWZLr6cgzNM9heCx7Q0UqJkBTqasiS1gNnYAeLSYqXd0PTw0bUE+XItPCLIX+0Y)
            scope: email
          kakao:
            client-id: ENC(uNd/J/dlaSuNsJ6BFMgUNIrZ5lXhMPEvNYduZ96tIEm3V5uimMKJpAcuGUk70yYi)
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

token:
  request:
    uri: '/token'
