spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: ENC(tECcRtMQeSYyaKTnlkhdpAYkU+yzAHwZ4CmOjtrbr3Q43qzY8lzQ3+RsB7EO4X+S0x+g2x7dSt9YQPGbQuZ3hQ==)
          kakao:
            redirect-uri: ENC(g6PLrzx8uNa3i/8+MCmukCP7NZ9icQjdhrtWV6FWaTyiogLuiNuoiJ9e1n0Ee8v43rhtiPqW4hp8wih171I7zg==)

oauth2:
  success:
    redirect_uri: 'https://dev.gohigher.site'
