spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: http://52.79.35.2:8080/oauth2/callback/google
          kakao:
            redirect-uri: http://52.79.35.2:8080/oauth2/callback/kakao

oauth2:
  success:
    redirect_uri: 'https://gohigher.site'
