spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect_uri: ENC(0F8OR5RcHaWaeIs6VnWKVKRapXeUFMuzdzIuG5Tr2rA9nenvAF7ietWR8Rp8cgHNyEzesbA9SeJYmewHeRpQAafz0sUlmUQi)
          kakao:
            redirect-uri: ENC(HQIheVkcWP/ImMka9jmNyfwYtjDLukolL8Tt07wkxGnC1JAWBLyERzBA+kZsYKBujuXASj6em+Ju599YfQwqB2XG4m0tgd8C)

oauth2:
  success:
    redirect_uri: 'http://localhost:3000'
