spring:
  datasource:
    username: gohigher
    password: password
    url: jdbc:mysql://localhost:3306/gohigher?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
