spring:
  datasource:
    username: ENC(wFv6AbWOSF4sKaLtpnmfvUIdWdEHBvyV)
    password: ENC(tszwsZ/646DuyrTKUamjCun33QYr+6sN)
    url: ENC(NP4rH1Hmp6zgdqEpoddbI2KFdcaqnvC7H3Td9GK/0MxaCCunHK5BlAu3/V7T1N1Tp2cgJhBZJkfXKOcJhiE31RFUhGqRX/dj1Kn386xKeRc0peYyrvKa39NUB0iAtX4B/e9FKjhBK3zu8ue+RfSvmfu68Wuz5qQawIm6aIIig6dfEXNf10m7Kg4ZYdWhslijSU//4xb4PcY=)
  jpa:
    hibernate.ddl-auto: validate
