spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
    hibernate:
      ddl-auto: create # ddl-auto
    datasource:
      hikari:
        maximum-pool-size: 5

  datasource:
    url: jdbc:h2:~/gohiger
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate:
      SQL: debug
