name: gohigher-backend-ci

on:
  pull_request:
    branches:
      - main
      - develop
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Change gradlew permission
        run: sudo chmod 755 gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -Dencryption-key=${{ secrets.ENCRYPTION_KEY }}
